version: "3.9"

services:
  web:
    build: .
    image: interviewproject:v1.0.0
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    container_name: interview_manager
    env_file:
      - ./.env.dev
